### ISSUE TITLE
VidSource Down

### ISSUE THREAD

**Issue by Kay-Tan** [marcojetson/IMDb-stream#1]
It seems VidSource is no longer operational. Do you have any plans to update this plugin? There are similar movie APIs to VidSource like [this one](https://hydramovies.com/openload-movies-api/). There are many more too. It would be good to see it operational again.

**Comment by marcojetson** [comment]
hey, thanks for the tip.
I've looked into the link you provided and what I don't like is that you cannot really tell if the stream works or not until you hit play. I'm looking into the providers they use for alternatives.

**Comment by Kay-Tan** [comment]
Sure, they use ODB API, VideoSpider.in and AKAPlayer in the movie player. I think they all work in a similar way but one of those on its own may be a better fit. There are premium ones of course but they cost $$$. Good luck with it.
